services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: instantmessenger_app
    restart: unless-stopped
    ports:
      - "8088:8000"
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - backend

networks:
  backend:
    driver: bridge
