services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app-messenger
    ports:
      - "8000:8000"
    command: "uvicorn app.server.main:app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ..:/fastapi-messenger
    networks:
      - backend

networks:
  backend:
    driver: bridge